apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ny_sub_turnstiles
    user: airflow
    secureJsonData:
      password: airflow
    isDefault: true
    editable: true
