name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Run unit tests with pytest
      run: |
        pytest tests/ --tb=short --disable-warnings

    - name: Run flake8 linter
      run: |
        pip install flake8
        flake8 . \
          --max-line-length=89 \
          --exclude .venv,venv,__pycache__,.mypy_cache,.pytest_cache

    - name: Run black formatter check
      run: |
        pip install black
        black . --check --line-length 89 --exclude '/(\.venv|venv|__pycache__)/'
